[package]
name = "lsm-db-tutorial-smol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nanoserde = "0.1.37"
smol = "2.0.0"

[dev-dependencies]
eyre = "0.6.12"
